### ISSUE TITLE
Flaky test "test_movement_no_action"

### ISSUE THREAD

**Issue by ra314** [ra314/deterministic-risk#88]
This test has passed and failed in two separate commits that make no change to anything related to movement.
Need to unflake the test.

**Comment by RifleDLuffy** [comment]
Reset()'s loop function was trying to loop over a list while editing it. Causing it to break early.
Sometimes, a country would spawn in just the right place to fuck up the test.

**Old**
```
for country in owned_countries:
		country.change_ownership_to(country.Game_Manager.player_neutral)
```
**New**
```
for country in [] + owned_countries:
		country.change_ownership_to(country.Game_Manager.player_neutral)
```
